// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDT4wMFNqpqnQH3gfsLa__uC22Y6w6og4',
    appId: '1:580683868741:web:99be93d12e6c8466d0512c',
    messagingSenderId: '580683868741',
    projectId: 'clammeditation',
    authDomain: 'clammeditation.firebaseapp.com',
    storageBucket: 'clammeditation.appspot.com',
    measurementId: 'G-2LWF6VVWQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_6APZO6-NsUt-Z3BSkcDQUtPpD0p0Gck',
    appId: '1:580683868741:android:6976d150c3f931e0d0512c',
    messagingSenderId: '580683868741',
    projectId: 'clammeditation',
    storageBucket: 'clammeditation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXHJVvFn6F6N-3WZRa80lSmsn-IBsBie0',
    appId: '1:580683868741:ios:23e4a16dc4da7b7bd0512c',
    messagingSenderId: '580683868741',
    projectId: 'clammeditation',
    storageBucket: 'clammeditation.appspot.com',
    iosBundleId: 'com.example.meditation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXHJVvFn6F6N-3WZRa80lSmsn-IBsBie0',
    appId: '1:580683868741:ios:23e4a16dc4da7b7bd0512c',
    messagingSenderId: '580683868741',
    projectId: 'clammeditation',
    storageBucket: 'clammeditation.appspot.com',
    iosBundleId: 'com.example.meditation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDT4wMFNqpqnQH3gfsLa__uC22Y6w6og4',
    appId: '1:580683868741:web:a8b44dae6885a80ad0512c',
    messagingSenderId: '580683868741',
    projectId: 'clammeditation',
    authDomain: 'clammeditation.firebaseapp.com',
    storageBucket: 'clammeditation.appspot.com',
    measurementId: 'G-J3P6845P8C',
  );
}
